### ISSUE TITLE
tomcat6 support

### ISSUE THREAD

**Issue by silverprize** [PeteGoo/tcSlackBuildNotifier#44]
Hi
I've faced problem with tomcat6.
[tomcat6 can't find custom EL function without prefix.](http://stackoverflow.com/questions/18961316/the-function-getmessagedata-must-be-used-with-a-prefix-when-a-default-namespace)
Do you have plan to support tomcat6?

tomcat6 log
---

`
May 04, 2015 9:50:43 AM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet buildServer threw exception
org.apache.jasper.JasperException: /plugins/tcSlackNotifications/SlackNotification/projectSlackNotificationTab.jsp(14,4) The function isEnabled must be used with a prefix when a default namespace is not specified
        at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:40)
        at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:407)
        at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:148)
        at org.apache.jasper.compiler.Validator$ValidateVisitor$1FVVisitor.visit(Validator.java:1528)
        at org.apache.jasper.compiler.ELNode$Function.accept(ELNode.java:131)
        at org.apache.jasper.compiler.ELNode$Nodes.visit(ELNode.java:206)
        at org.apache.jasper.compiler.ELNode$Visitor.visit(ELNode.java:248)
        at org.apache.jasper.compiler.ELNode$Root.accept(ELNode.java:56)
        at org.apache.jasper.compiler.ELNode$Nodes.visit(ELNode.java:206)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.validateFunctions(Validator.java:1553)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.getJspAttribute(Validator.java:1326)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.checkXmlAttributes(Validator.java:1176)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:840)
        at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1530)
        at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2361)
        at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2411)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:859)
        at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1530)
        at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2361)
        at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2411)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:859)
`

**Comment by mattgibson** [comment]
Just ran into this too. Works if you upgrade to Tomcat 7.

**Comment by silverprize** [comment]
@mattgibson :cry: I know.
But unfortunately i don't have permission to touch tomcat.
I'll customize it.
Thank you.
