### ISSUE TITLE
Problem with proxy authentication

### ISSUE THREAD

**Issue by un1kum** [PeteGoo/tcSlackBuildNotifier#77]
When using proxy authentication, every test sending a notification fails:

````
[2016-03-29 16:19:10,070]  ERROR -   jetbrains.buildServer.SERVER - Error java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.<init>(I)V while processing request:...
java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.<init>(I)V
	at org.apache.http.impl.auth.BasicScheme.<init>(BasicScheme.java:65)
	at org.apache.http.impl.auth.BasicSchemeFactory.create(BasicSchemeFactory.java:68)
	at org.apache.http.impl.client.AuthenticationStrategyImpl.select(AuthenticationStrategyImpl.java:175)
	at org.apache.http.impl.client.ProxyAuthenticationStrategy.select(ProxyAuthenticationStrategy.java:43)
	at org.apache.http.impl.auth.HttpAuthenticator.handleAuthChallenge(HttpAuthenticator.java:154)
	at org.apache.http.impl.execchain.MainClientExec.createTunnelToTarget(MainClientExec.java:466)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at slacknotifications.SlackNotificationImpl.postViaApi(SlackNotificationImpl.java:192)
	at slacknotifications.SlackNotificationImpl.post(SlackNotificationImpl.java:152)
...
````

It seems to me that plugin require commons-codec version higher that teamcity bundled version. Attempt to up library version in teamcity leads to endless upgrade all builds agents.

**Comment by pointerxr** [comment]
This can be resolved by running the plugin in a different context.

**Comment by stijnvanbever** [comment]
> This can be resolved by running the plugin in a different context.

Sorry to reply on this old bug. But can you explain how to run a plugin in a different context?
I'm facing with the same issue on TeamCity 10.0.4 (build 42538)
